/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SoundExperienceRouteImport } from './routes/sound-experience'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as RepairServiceRouteImport } from './routes/repair-service'
import { Route as OurWorkRouteImport } from './routes/our-work'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopIndexRouteImport } from './routes/shop.index'
import { Route as ShopProductIdRouteImport } from './routes/shop.$productId'
import { Route as ShopCategorySlugRouteImport } from './routes/shop.category.$slug'

const SoundExperienceRoute = SoundExperienceRouteImport.update({
  id: '/sound-experience',
  path: '/sound-experience',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const RepairServiceRoute = RepairServiceRouteImport.update({
  id: '/repair-service',
  path: '/repair-service',
  getParentRoute: () => rootRouteImport,
} as any)
const OurWorkRoute = OurWorkRouteImport.update({
  id: '/our-work',
  path: '/our-work',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopProductIdRoute = ShopProductIdRouteImport.update({
  id: '/shop/$productId',
  path: '/shop/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopCategorySlugRoute = ShopCategorySlugRouteImport.update({
  id: '/shop/category/$slug',
  path: '/shop/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/our-work': typeof OurWorkRoute
  '/repair-service': typeof RepairServiceRoute
  '/reviews': typeof ReviewsRoute
  '/sound-experience': typeof SoundExperienceRoute
  '/shop/$productId': typeof ShopProductIdRoute
  '/shop/': typeof ShopIndexRoute
  '/shop/category/$slug': typeof ShopCategorySlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/our-work': typeof OurWorkRoute
  '/repair-service': typeof RepairServiceRoute
  '/reviews': typeof ReviewsRoute
  '/sound-experience': typeof SoundExperienceRoute
  '/shop/$productId': typeof ShopProductIdRoute
  '/shop': typeof ShopIndexRoute
  '/shop/category/$slug': typeof ShopCategorySlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/our-work': typeof OurWorkRoute
  '/repair-service': typeof RepairServiceRoute
  '/reviews': typeof ReviewsRoute
  '/sound-experience': typeof SoundExperienceRoute
  '/shop/$productId': typeof ShopProductIdRoute
  '/shop/': typeof ShopIndexRoute
  '/shop/category/$slug': typeof ShopCategorySlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/our-work'
    | '/repair-service'
    | '/reviews'
    | '/sound-experience'
    | '/shop/$productId'
    | '/shop/'
    | '/shop/category/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/our-work'
    | '/repair-service'
    | '/reviews'
    | '/sound-experience'
    | '/shop/$productId'
    | '/shop'
    | '/shop/category/$slug'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/our-work'
    | '/repair-service'
    | '/reviews'
    | '/sound-experience'
    | '/shop/$productId'
    | '/shop/'
    | '/shop/category/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  OurWorkRoute: typeof OurWorkRoute
  RepairServiceRoute: typeof RepairServiceRoute
  ReviewsRoute: typeof ReviewsRoute
  SoundExperienceRoute: typeof SoundExperienceRoute
  ShopProductIdRoute: typeof ShopProductIdRoute
  ShopIndexRoute: typeof ShopIndexRoute
  ShopCategorySlugRoute: typeof ShopCategorySlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sound-experience': {
      id: '/sound-experience'
      path: '/sound-experience'
      fullPath: '/sound-experience'
      preLoaderRoute: typeof SoundExperienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repair-service': {
      id: '/repair-service'
      path: '/repair-service'
      fullPath: '/repair-service'
      preLoaderRoute: typeof RepairServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-work': {
      id: '/our-work'
      path: '/our-work'
      fullPath: '/our-work'
      preLoaderRoute: typeof OurWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/shop'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$productId': {
      id: '/shop/$productId'
      path: '/shop/$productId'
      fullPath: '/shop/$productId'
      preLoaderRoute: typeof ShopProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/category/$slug': {
      id: '/shop/category/$slug'
      path: '/shop/category/$slug'
      fullPath: '/shop/category/$slug'
      preLoaderRoute: typeof ShopCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  OurWorkRoute: OurWorkRoute,
  RepairServiceRoute: RepairServiceRoute,
  ReviewsRoute: ReviewsRoute,
  SoundExperienceRoute: SoundExperienceRoute,
  ShopProductIdRoute: ShopProductIdRoute,
  ShopIndexRoute: ShopIndexRoute,
  ShopCategorySlugRoute: ShopCategorySlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
